### ISSUE TITLE
Replication may leave out blobs on reconstruction corner cases

### ISSUE THREAD

**Issue by nsivabalan** [linkedin/ambry#507] opened 2016-12-06 17:59 UTC
Replication relies on the fact that the ordering of keys does not change inside the index. This is mostly true except in the case of reconstruction. During reconstruction, a corner case may cause replication to leave out blobs. The conditions that have to be met are:

1. Replica R2 is replicating R1 and has an index based store token with index segment start offset: IS and key: K (IS, K) that refers to its current replication position in R1.
2. Replica R1 suffers a disk failure and starts reconstruction.
3. Replica R2 presents its token (IS, K) to R1.

There are multiple things that can happen here
1. If log size of R1 < IS, the token is reset and there is no problem.
2. If log size of R1 > IS and IS is no longer a valid index segment start offset - Replication does not make progress and manual intervention required to fix the problem.
3. If log size of R1 > IS and IS is a valid index segment start offset - Replication may miss a few blobs because of reordering of keys - This is the really bad case.

This might happen even in case of journal based token and the way the replica might respond to the replica metadata request is 
1. If log size of R1 < offset(journal based), the token is reset and there is no problem.
2. If log size of R1 > offset(journal based) and if we do find the offset in current journal, replication might proceed as usual thinking that the offset is good. This is also as we might leave out some blobs.
3. If log size of R1 > offset(journal based) and if offset is not found in the journal, the store will try to locate the index segment closest to the token offset and will start returning entries from the start of that segment. This again, is bad as it might leave out some blobs.

To fix this bug, a replica needs to know that it is under reconstruction. 

AC:
1. Design for fixing this bug.
2. The actual bug fix.
3. Tested - While the scenario is hard to induce, it should be verified that normal replication proceeds smoothly and all the "bad" cases have been reasoned at least theoretically.

**Comment by pnarayanan** [comment] 2016-12-06 18:20
Just a note: though this affects replication, the bug is (and the fix will go) in the store, and it should be possible to test this scenario as part of `testFindEntriesSince()` or something similar.

As for the scenario - I think you need to edit number 3. under "there are multiple things that can happen here". Also, this can also happen if the token is in the journal.

I think the first thing to do as part of fixing this is to reproduce the scenario in the tests - this way we will know exactly what we are fixing.

**Comment by nsivabalan** [comment] 2016-12-06 18:26
The crux is that each replica should have some way of figuring out that it is under re-creation or has taken a new incarnation. This also means that the token transmitted during replication should contain information referring to the incarnation. So the plan to to introduce an incarnation id to every replica/store that uniquely identifies an incarnation of the store. This incarnation Id will only be reset during recreation of the store. At all other times,(regular progress or node crash), the incarnation Id remains the same and never modified. This incarnation id is also attached to the token sent out during replication. So, whenever any replica receives the token from some other replica for replication purposes, first step is to check if incarnation id matches. If not, this replica should just reset the token to 0 and respond back, as the token received was from an old incarnation. If the incarnation Id matches, then the store can proceed as usual responding to replica metadata requests. 

Where and how to store the Incarnation Id:
     The plan is to store this incarnation id in a new file called store descriptor. Until now Ambry’s store or replica doesn’t have any information like a store descriptor. Store descriptor is something that uniquely identifies the store with some additional metadata information about the store. For now, we plan to keep it simple by having just the partition information that the store refers to and the Incarnation Id. In future, this might evolve to have more metadata information about the store, like log segment size, state of the partition and so on.

**Comment by xiahome** [comment] 2016-12-06 19:41
The proposal should work. One question, will this incarnation id be used only for replication? The id itself seems to be generally-purposed.

**Comment by nsivabalan** [comment] 2016-12-07 18:17
Here is the patch : https://github.com/linkedin/ambry/pull/511

@xiahome : For now, we plan to use it only for replication purposes. But we do forsee it evolving to hold more information in future

**Comment by vgkholla** [comment] 2017-02-08 23:25
Fixed in #511

**Closed by vgkholla** 2017-02-08 23:25 UTC
Labels: bug
