### ISSUE TITLE
Test failure: com.github.ambry.server.ServerSSLTest > endToEndCloudBackupTest[1] FAILED

### ISSUE THREAD

**Issue by justinlin-linkedin** [linkedin/ambry#1639] opened 2020-10-02 05:46 UTC
Stacktrace
```
com.github.ambry.server.ServerSSLTest > endToEndCloudBackupTest[1] FAILED
    java.lang.NullPointerException
        at com.github.ambry.server.MockNotificationSystem.awaitBlobCreations(MockCluster.java:676)
        at com.github.ambry.server.ServerTestUtil.endToEndCloudBackupTest(ServerTestUtil.java:672)
        at com.github.ambry.server.ServerSSLTest.endToEndCloudBackupTest(ServerSSLTest.java:149)
```

Gradle scan
https://gradle.com/s/lafzlgld7tsqy

**Comment by lightningrob** [comment] 2020-10-09 01:47
Fix needed in MockCluster.awaitBlobCreations()

**Comment by lightningrob** [comment] 2020-10-09 01:53
Duplicate of #1415

**Closed by lightningrob** 2020-10-09 01:53 UTC
Labels: test-failure
